### ISSUE TITLE
All RKI Covid Entitities are unavailable today

### ISSUE THREAD

**Issue by LuckyTriple7** [thebino/rki_covid#51] opened 2021-07-30 11:06 UTC
**🐛 Describe the bug**

All Entities atre unavailable since today.

**💥 When did the bug occurred.***
- [ ] Installation / First-run
- [ ] Configuration
- [X] Other

**👣 To Reproduce**

**💻 Versions (please complete the following information):**

 - HA 2021.07.03

**🗄 Logfiles (Configuration > Logs)**

```
2021-07-30 12:59:10 ERROR (MainThread) [custom_components.rki_covid] Unexpected error fetching rki_covid data: unsupported operand type(s) for +=: 'int' and 'NoneType'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/rki_covid/__init__.py", line 78, in async_get_districts
    await parser.load_data()
  File "/usr/local/lib/python3.9/site-packages/rki_covid_parser/parser.py", line 26, in load_data
    await self._merge_states()
  File "/usr/local/lib/python3.9/site-packages/rki_covid_parser/parser.py", line 132, in _merge_states
    self.states[district.state].recovered += district.recovered
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
```

**Comment by damanti-me** [comment] 2021-07-30 11:14
same here!

**Comment by mi4mac** [comment] 2021-07-30 12:29
same here

**Comment by oli737** [comment] 2021-07-31 12:20
same here

**Comment by LuckyTriple7** [comment] 2021-07-31 17:28
No idea why, but it works again:
- Delete All Entitities in HA Integration Menu
- Uninstall RKI Covid via HACS
- Restart HA
- Install RKI Covid via HACS
- Restart HA
- Add RKI Covid Entities in HA Integration Menu

![image](https://user-images.githubusercontent.com/60685158/127747904-e011fdb2-b59b-4023-b14a-ff1bd7029abf.png)

**Comment by damanti-me** [comment] 2021-07-31 21:20
> No idea why, but it works again:
> 
> - Delete All Entitities in HA Integration Menu
> 
> - Uninstall RKI Covid via HACS
> 
> - Restart HA
> 
> - Install RKI Covid via HACS
> 
> - Restart HA
> 
> - Add RKI Covid Entities in HA Integration Menu
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/60685158/127747904-e011fdb2-b59b-4023-b14a-ff1bd7029abf.png)
> 
> 

I can confirm. Did as suggested and it works again. 
Thanks !

**Comment by thebino** [comment] 2021-08-01 14:03
1st this is not an issue of this integration. It is part of the [rki-covid-parser](https://github.com/thebino/rki-covid-parser/)
2nd it looks like, the rki offered invalid data, which couldn't been parsed. I thought about handling invalid data, but what should the parser or the integration do with invalid data, so I'll just ignore this and hopefully no invalid data will be released to public in the future.

**Closed by thebino** 2021-08-01 14:03 UTC
