### ISSUE TITLE
RKI covid numbers are set at "0" since Feb. 15

### ISSUE THREAD

**Issue by Kepana808** [thebino/rki_covid#80] opened 2022-02-21 19:13 UTC
Since a while I have only showing "0" at the daily new cases for Germany, Bayern, LK Lindau, the weekly incidence per 100k, is alright.

Then I looked for all the sensor data , and only 4 of 8 data are updated.

Could that be a bug in the system, or are they not anymore updated from RKI. The data are still available on the RKI webpage?

Thanks for looking into this problem and your support.

![Bildschirmfoto 2022-02-21 um 09 00 07](https://user-images.githubusercontent.com/82287071/155014372-989b5cff-4428-48be-bc22-fac17177b7c3.png)

**Comment by thebino** [comment] 2022-02-21 21:42
duplicate of #79

**Closed by thebino** 2022-02-21 21:42 UTC
