### ISSUE TITLE
Nach Neustart HA Entitäten nicht verfügbar

### ISSUE THREAD

**Issue by Dog6574** [thebino/rki_covid#39] opened 2021-04-19 08:03 UTC
Hallo.

Wenn die Integration HA hinzugefügt wird und danach der Server neu gestartet wird sind die Entitäten nicht mehr verfügbar.
Der Fehler ist beliebig oft reproduzierbar.

HA neuste Version mit allen Updates.

Gruß,

**Comment by damanti-me** [comment] 2021-04-19 08:11
I agree. Think i got the same issue. 
```
Traceback (most recent call last):
 File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 205, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/rki_covid/sensor.py", line 101, in async_setup_entry
    sensors = [
  File "/config/custom_components/rki_covid/sensor.py", line 102, in <listcomp>
    RKICovidNumbersSensor(coordinator, district, info_type) for info_type in SENSORS
  File "/config/custom_components/rki_covid/sensor.py", line 123, in __init__
    data = coordinator.data[district]
TypeError: 'NoneType' object is not subscriptable
```
Thought i is fixed now... moving back to beta..

**Comment by thebino** [comment] 2021-04-19 08:33
Can you please use the bug report template and provide additional logs.

**Comment by damanti-me** [comment] 2021-04-19 08:54
**🐛 Describe the bug**

The RKI Sensor did not come up again after the update to 1.5.1. Cant add any other RKI sensor, receiving "

Der Konfigurationsfluss konnte nicht geladen werden
"


**💥 When did the bug occurred.***
- [ ] Installation / First-run
- [ ] Configuration
- [x] Other (update to newest version)

**👣 To Reproduce**

Steps to reproduce the behavior:
Just update to 1.5.1 


**🧐 Expected behavior**

no error should appear after regular update

**💻 Versions (please complete the following information):**

 - OS: [core-2021.4.5]
 - Supervisor: [supervisor-2021.04.0]
 - Browser [firefox]

**🗄 Logfiles (Configuration > Logs)**

> 🎓 Increase the log level for this custom integration by adding the following lines to the `configuration.yaml`
```
2021-04-19 10:44:14 ERROR (MainThread) [custom_components.rki_covid] Error fetching rki_covid data: Error reading data from rki-covid-parser: 
2021-04-19 10:44:17 DEBUG (MainThread) [custom_components.rki_covid.sensor] setup sensor for platform
2021-04-19 10:44:17 DEBUG (MainThread) [custom_components.rki_covid.sensor] initialize count sensor for SK Oldenburg
2021-04-19 10:44:19 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up rki_covid platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 205, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/rki_covid/sensor.py", line 77, in async_setup_platform
    sensors = [
  File "/config/custom_components/rki_covid/sensor.py", line 78, in <listcomp>
    RKICovidNumbersSensor(coordinator, district[CONF_DISTRICT_NAME], info_type)
  File "/config/custom_components/rki_covid/sensor.py", line 123, in __init__
    data = coordinator.data[district]
TypeError: 'NoneType' object is not subscriptable

```
Add regarding log messages from the Logs for more details.

**Comment by michl270** [comment] 2021-04-19 08:57
same here - please advice how to use bug report template

**Comment by thebino** [comment] 2021-04-19 09:37
@damanti-me / @michl270 : What hardware are you using?

It looks like, the initial setup took longer then 10 seconds and got cancelled. I can only assume the reason for this. Could be a lacking internet connection or a performance issue based on the hardware.

**Comment by damanti-me** [comment] 2021-04-19 09:45
> 
> 
> @damanti-me / @michl270 : What hardware are you using?
> 
> It looks like, the initial setup took longer then 10 seconds and got cancelled. I can only assume the reason for this. Could be a lacking internet connection or a performance issue based on the hardware.

Maybe we can add the hardware  in the issue template. I'm using an RBP3+. https://github.com/home-assistant/core/pull/48924 regarding the 10 s.
It works a now after copy the old 1.4.1 from my backup (best thing i've ever done- regular time based backups 😄 🔙  )

**Comment by michl270** [comment] 2021-04-19 09:52
> @damanti-me / @michl270 : What hardware are you using?
> 
> It looks like, the initial setup took longer then 10 seconds and got cancelled. I can only assume the reason for this. Could be a lacking internet connection or a performance issue based on the hardware.

I am using a RPI4 with 8GB RAM

**Comment by Dog6574** [comment] 2021-04-19 11:36
Raspi 3B+ with SSD here

**Comment by thebino** [comment] 2021-04-19 14:55
Can one of you try to patch a file locally and do a reboot to see if it fixes the issue? 
I can't reproduce the issue myself, all requests and are done in 0,2 seconds. But perhaps it take longer on your side.

> /config/custom_components/rki_covid/__init__.py  line 76
```
with async_timeout.timeout(30):
```

**Comment by michl270** [comment] 2021-04-19 17:05
Thanks for your assistance - I have patched the file as described by you. Sensors are now working properly :-)

However, log files are stating the following warning:
2021-04-19 18:55:30 WARNING (MainThread) [homeassistant.setup] Setup of rki_covid is taking over 10 seconds.

**Closed** 2021-04-20 05:24 UTC
Labels: bug
